Repository DNPLab/DNPLab, pull requests merged in 2021-06, with the labels that each got.

#128 moved functions from dnpTools to dnpMath
  dnplab/dnpMath.py
  dnplab/dnpTools.py
  unittests/test_hydration.py
Labels: Clean

#130 Removing commented code + reformatting
  dnplab/dnpFit.py
  dnplab/dnpIO/prospa.py
  unittests/test_hydration.py
Labels: bug

#131 Updated experiment names in prospa import to support new pulse programs
  dnplab/dnpIO/prospa.py
Labels: bug

#132 Feature-Adding New ndalign function
  dnplab/dnpNMR.py
Labels: enhancement

#139 Cumulative Sum Method
  dnplab/core/nddata.py
Labels: enhancement
