Repository DNPLab/DNPLab, pull requests merged in 2022-10, with the labels that each got.

#246 Added depreciation warning to align
  dnplab/processing/align.py
Labels: Clean

#245 New helper functions
  dnplab/processing/__init__.py
  dnplab/processing/conversion.py
Labels: enhancement

#255 Adding manual phase function
  dnplab/io/topspin.py
  dnplab/math/lineshape.py
  dnplab/plotting/general.py
  dnplab/processing/align.py
  dnplab/processing/apodization.py
  dnplab/processing/conversion.py
  dnplab/processing/offset.py
  dnplab/processing/phase.py
Labels: enhancement

#252 Small changes to fancy_plot
  dnplab/plotting/general.py
Labels: enhancement

#249 Updated docstrings
  dnplab/constants/radicalProperties.py
  dnplab/plotting/general.py
  dnplab/plotting/image.py
  dnplab/processing/align.py
  dnplab/processing/integration.py
Labels: documentation, Clean

#256 Changed import of numpy
  dnplab/analysis/hydration.py
  dnplab/core/base.py
  dnplab/core/coord.py
  dnplab/core/data.py
  dnplab/core/ufunc.py
  dnplab/core/util.py
  dnplab/fitting/general.py
  dnplab/io/bes3t.py
  dnplab/io/cnsi.py
  dnplab/io/delta.py
  dnplab/io/h5.py
  dnplab/io/power.py
  dnplab/io/prospa.py
  dnplab/io/random.py
  dnplab/io/specman.py
  dnplab/io/tnmr.py
  dnplab/io/topspin.py
  dnplab/io/vna.py
  dnplab/io/vnmrj.py
  dnplab/io/winepr.py
  dnplab/math/lineshape.py
  dnplab/math/relaxation.py
  dnplab/math/window.py
  dnplab/plotting/stack_plot.py
  dnplab/processing/align.py
  dnplab/processing/apodization.py
  dnplab/processing/fft.py
  dnplab/processing/helpers.py
  dnplab/processing/offset.py
  dnplab/widgets/manual_align.py
  dnplab/widgets/manual_phase.py
Labels: enhancement, Clean
